# Generated by Django 4.2.3 on 2023-07-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
